name: "Check PR title"

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    uses: health-informatics-uon/workflows/.github/workflows/pr-title.yml@f37845ddc7c7e8a2aaff2af07ce053fcf639f9c6 # v 1.5.3
    permissions:
      pull-requests: read
